# 2.20 Numpy


In [1]:
import numpy as np
#mengimpor numpy serta menggunakan nama alias np agar tidak kepanjangan dalam mengetik

# 2.20.1 Perintah Dasar pada Numpy

In [2]:
import numpy as np
# membuat array dengan numpy
print('Output array 1 dimensi: ')
b_36 = np.array([2,4,6,8,10])
print(b_36)
print('----------------------------------------------')

print('Output array 2 dimensi: ')
c_36 = np.array([[12,14,16,18],[20,18,16,14]])
print(c_36)
print('----------------------------------------------')

print('Output array 3 dimensi: ')
d_36 = np.array([[[2,4,6,8],[10,12,14,16]],
                  [[18,20,18,16],[14,12,10,8]],
                  [[4,6,8,10],[12,14,16,18]]])
print(d_36)
print('----------------------------------------------')

#mengakses data array
print('Output data array b dengan indeks 2 adalah: ')
print(b_36[2])           #mengakses data pada array pada numpy sama seperti list
print('Output data array b dengan indeks 4 adalah: ')
print(b_36[4])
print('Output data array b dengan indeks 3 adalah: ')
print(b_36[3])

Output array 1 dimensi: 
[ 2  4  6  8 10]
----------------------------------------------
Output array 2 dimensi: 
[[12 14 16 18]
 [20 18 16 14]]
----------------------------------------------
Output array 3 dimensi: 
[[[ 2  4  6  8]
  [10 12 14 16]]

 [[18 20 18 16]
  [14 12 10  8]]

 [[ 4  6  8 10]
  [12 14 16 18]]]
----------------------------------------------
Output data array b dengan indeks 2 adalah: 
6
Output data array b dengan indeks 4 adalah: 
10
Output data array b dengan indeks 3 adalah: 
8


In [3]:
b_36.ndim #ndim digunakan untuk mengecek dimensi pada array

1

In [4]:
c_36.ndim

2

In [5]:
d_36.ndim

3

In [6]:
b_36.shape

(5,)

In [7]:
c_36.shape

(2, 4)

In [8]:
d_36.shape #shape digunakan untuk mengecek dimensi, baris dan kolom suatu array

(3, 2, 4)

In [9]:
import numpy as np
print('Output array 1 dimensi: ')
x_36 = np.array([1,3,5,7,9])
print(x_36)
print('----------------------------------------------')

print('Output array 2 dimensi: ')
y_36 = np.array([[11,13,15,17],[19,21,23,25]])
print(y_36)
print('----------------------------------------------')

print('Output array 3 dimensi: ')
z_36 = np.array([[[1,3,5,7],[9,11,13,15]],
                  [[17,19,17,15],[13,11,9,7]],
                  [[3,5,7,9],[11,13,15,17]]])
print(z_36)
print('----------------------------------------------')

#mengakses data array
print('Output data array x dengan indeks 1 adalah: ')
print(x_36[1])
print('Output data array x dengan indeks 3 adalah: ')
print(x_36[3])
print('Output data array x dengan indeks 4 adalah: ')
print(x_36[4])

Output array 1 dimensi: 
[1 3 5 7 9]
----------------------------------------------
Output array 2 dimensi: 
[[11 13 15 17]
 [19 21 23 25]]
----------------------------------------------
Output array 3 dimensi: 
[[[ 1  3  5  7]
  [ 9 11 13 15]]

 [[17 19 17 15]
  [13 11  9  7]]

 [[ 3  5  7  9]
  [11 13 15 17]]]
----------------------------------------------
Output data array x dengan indeks 1 adalah: 
3
Output data array x dengan indeks 3 adalah: 
7
Output data array x dengan indeks 4 adalah: 
9


In [10]:
x_36.ndim

1

In [11]:
y_36.ndim

2

In [12]:
z_36.ndim

3

In [13]:
x_36.shape

(5,)

In [14]:
y_36.shape

(2, 4)

In [15]:
z_36.shape

(3, 2, 4)

# 2.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [16]:
e_36 = np.array([[1,3,5,7],[9,11,13,15],[17,19,21,23]]) #menginisialisasi variabel
print(e_36)                                             #mencetak array

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [17]:
e_36[0,3] #indeks pada python selalu dimulai dari 0, maka ini akan mencetak elemen array e yang berada di baris 1 kolom 4

7

In [18]:
e_36[1,3] #mencetak elemen array e yang berada di baris 2 kolom 4

15

In [19]:
e_36[1,:] #untuk mencetak semua elemen pada baris kedua

array([ 9, 11, 13, 15])

In [20]:
e_36[:,2] #untuk mencetak semua elemen pada kolom ketiga

array([ 5, 13, 21])

In [21]:
e_36[0,1:3]

array([3, 5])

In [22]:
e_36[0,0:3:2]  #untuk baris pertama, kolom pertama sampai kolom tiga dengan loncatan dua

array([1, 5])

In [23]:
e_36[0,0] = 55 #ketika ingin mengubah suatu elemen pada array
print(e_36) #untuk mencetak perintah

[[55  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [24]:
e_36[0,0] = 155
print(e_36)

[[155   3   5   7]
 [  9  11  13  15]
 [ 17  19  21  23]]


In [25]:
k_36 = np.array([[14,15,16,17],[18,19,20,21],[22,23,24,25]])
print(k_36)
print('=================================================================')

print(k_36[0,3])
print('=================================================================')

print(k_36[1,3])
print('=================================================================')

print(k_36[1,:])
print('=================================================================')

print(k_36[:,2])
print('=================================================================')

print(k_36[0,1:3])
print('=================================================================')

print(k_36[0,0:3:2])
print('=================================================================')

k_36[0,0] = 40
print(k_36)

[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
17
21
[18 19 20 21]
[16 20 24]
[15 16]
[14 16]
[[40 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


## 2.20.3 Matrix pada Numpy

beberapa perintah dalam Numpy untuk membuat matrix

In [26]:
#np.ones((...,...))
#mencetak matriks dengan anggota 1, dengan baris dan kolom sesuai dengan yang diperintahkan
print('Output matriks anggota 1 dengan baris 3 dan kolom 4: ')
np.ones((3,4))

Output matriks anggota 1 dengan baris 3 dan kolom 4: 


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
#np.zeros((...,...))
#mencetak matriks dengan anggota 0, dengan baris dan kolom sesuai dengan yang diperintahkan
print('Output matriks anggota 0 dengan baris 4 dan kolom 3: ')
np.zeros((4,3))

Output matriks anggota 0 dengan baris 4 dan kolom 3: 


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#np.identity((...,...))
#mencetak matriks identitas, dengan baris dan kolom sesuai dengan yang diperintahkan
print('Output matriks identitas 5 x 5 : ')
np.identity(5)

Output matriks identitas 5 x 5 : 


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#np.ones(...,...,...)
#mencetak matriks dengan anggota 1, dengan jumlah, baris dan kolom sesuai dengan yang iperintahkan
print('Output matriks anggota 1 dengan jumlah matriks 3, 4 baris dan 5 kolom: ')
print(np.ones((3,4,5)))

Output matriks anggota 1 dengan jumlah matriks 3, 4 baris dan 5 kolom: 
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [30]:
#np.full((...,...),...)
#mencetak matriks dengan anggota pada indeks keempat, dengan jumlah, baris dan kolom sesuai yang diperintahkan
print('Output matriks anggota 9 dengan 4 baris dan 3 kolom: ')
np.full((4,3),9)

Output matriks anggota 9 dengan 4 baris dan 3 kolom: 


array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [31]:
#np.random.rand(...,...)
#mencetak matriks yang anggotanya random
print('Output matriks anggota random dengan 4 baris dan 3 kolom: ')
print(np.random.rand(4,3))

Output matriks anggota random dengan 4 baris dan 3 kolom: 
[[0.03676805 0.6999509  0.704989  ]
 [0.6806176  0.10219893 0.77109648]
 [0.84179636 0.74373232 0.2379246 ]
 [0.79854766 0.37843675 0.79550058]]


In [32]:
#np.random.randit(...,..., size=(...,...))
#mencetak matriks yang anggotanya acak dengan tipe data integer acak dari ukuran yang diberikan
print('Output matriks anggota random integer 1-10 dengan 3 baris dan 4 kolom: ')
print(np.random.randint(1,10,size=(3,4)))

Output matriks anggota random integer 1-10 dengan 3 baris dan 4 kolom: 
[[5 1 1 8]
 [2 5 6 1]
 [8 2 8 1]]


In [33]:
print('Output matriks anggota 1 dengan baris 4 dan kolom 5 : ')
print(np.ones((4,5)))

print()

print('Output matriks anggota 0 dengan baris 5 dan kolom 4: ')
print(np.zeros((5,4)))

print()

print('Output matriks identitas 6 x 6: ')
print(np.identity(6))

print()

print('Output matriks anggota 1 dengan jumlah matriks 4, 5 baris dan 6 kolom : ')
print(np.ones((4,5,6)))

print()

print('Output matriks anggota 10 dengan 5 baris dan 4 kolom : ')
print(np.full((5,4),10))

print()

print('Output matriks anggota random dengan 5 baris dan 4 kolom : ')
print(np.random.rand(5,4))

print()

print('Output matriks anggota random integer 1-15 dengan 4 baris dan 5 kolom : ')
print(np.random.randint(1,15,size=(4,5)))

Output matriks anggota 1 dengan baris 4 dan kolom 5 : 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Output matriks anggota 0 dengan baris 5 dan kolom 4: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Output matriks identitas 6 x 6: 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Output matriks anggota 1 dengan jumlah matriks 4, 5 baris dan 6 kolom : 
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]

Output matriks anggota 10 dengan 5 baris dan 4 kolom : 
[

latihan buat matriks ukuran 10 x 10 dengan Numpy

In [34]:
#membuat base matriks
d_36 = np.zeros((10,10))
print(d_36)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
#membuat base diagonal utama
i_36 = np.identity(10)
print(i_36)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [36]:
#mengganti diagonal dengan angka 9
v_36 = 9*i_36
print(v_36)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [37]:
a_36 = np.ones((8,8))    #membuat matriks 8 x 8 untuk bagian dalam matriks 10 x 10
f_36 = np.identity(8)*8  #membuat matriks identitas pada matriks 8 x 8
e_36 = a_36+f_36         #menggabungkan hasil a dan f
print(e_36)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [38]:
v_36[1:-1,1:-1] = e_36 #update v yaitu baris kedua sampai 9 menjadi e
print(v_36)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [39]:
l_36 = np.identity(6)*9     #membuat matriks identitas  6 x 6 dengan diagonal 9
v_36[2:-2,2:-2] = l_36      #update v yaitu baris ketiga sampai 8 menjadi l
print(v_36)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [40]:
z_36 = np.ones((4,4))*2    #membuat matriks 4 x 4 dengan elemen 2
b_36 = np.identity(4)*7    #membuat identitas 4 x 4 dengan elemen 7
g_36 = z_36 + b_36         #menggabungkan hasil z dan b
print(g_36)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [41]:
v_36[3:-3,3:-3] = g_36   #update v yaitu baris keempat sampai 7 menjadi g
print(v_36)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [42]:
n_36 = np.identity(2)*9    #membuat matriks identitas 2 x 2 dengan diagonal 9
print(n_36)

[[9. 0.]
 [0. 9.]]


In [43]:
v_36[4:-4,4:-4] = n_36    #update v yaitu baris kelima sampai 6 menjadi n
print(n_36)

[[9. 0.]
 [0. 9.]]


# 2.20.4 Copy pada Numpy

In [44]:
# Kasus yang tidak diinginkan
k_36 = np.array([2,3,5,7,11]) #menginisialisasi array k
print(k_36)

[ 2  3  5  7 11]


In [45]:
l_36 = k_36       #array l sama dengan k
print(l_36)

[ 2  3  5  7 11]


In [46]:
l_36[0] = 16     #mengubah array l dengan indeks 0 menjadi 16
print(l_36)

[16  3  5  7 11]


In [47]:
print(k_36)     #karena k = l, maka output yang tercetak akan sama

[16  3  5  7 11]


In [48]:
m_36 = np.array([2,3,5,7,11])  #menginisialisasi array dengan m
print(m_36)

[ 2  3  5  7 11]


In [49]:
n_36 = m_36.copy()      #mengcopy array m ke n
print(n_36)

[ 2  3  5  7 11]


In [50]:
n_36[0] = 16            #mengubah array n dengan indeks 0 menjadi 16
print(n_36)

[16  3  5  7 11]


In [51]:
print(m_36)            #karena array m dicopy ke n, maka elemen pada array m tidak ikut berubah

[ 2  3  5  7 11]


In [52]:
# Kasus yang tidak diinginkan
x_36 = np.array([11,12,13,14,15])
print(x_36)

y_36 = x_36
print(y_36)

y_36[0] = 8
print(y_36)

print (x_36)

[11 12 13 14 15]
[11 12 13 14 15]
[ 8 12 13 14 15]
[ 8 12 13 14 15]


In [53]:
z_36 = np.array([11,12,13,14,15])
print(z_36)

a_36 = z_36.copy()
print(a_36)

a_36[0] = 8
print(a_36)

print(z_36)

[11 12 13 14 15]
[11 12 13 14 15]
[ 8 12 13 14 15]
[11 12 13 14 15]


## 2.20.5 Operasi Matematika pada numpy

In [54]:
#operasi skalar dengan matriks
print('Ini adalah matriks yang akan dioperasikan :')
f_36 = np.array([1,2,3,4,5])      #menginisialisasi array f
print(f_36)
g_36 = np.array([6,7,8,9,10])     #menginisialisasi array g
print(g_36)

print('Berikut ini hasil dari penjumlahan matriks f dan g: ')
print(f_36+g_36)

print('Berikut ini hasil dari pengurangan matriks f dan g: ')
print(f_36-g_36)

print('Berikut ini hasil dari perkalian matriks f dan g: ')
print(f_36*g_36)

print('Berikut ini hasil dari pembagian matriks f dan g: ')
print(f_36/g_36)

print('Berikut ini hasil dari matriks g dipangkatkan f: ')
print(g_36**f_36)

Ini adalah matriks yang akan dioperasikan :
[1 2 3 4 5]
[ 6  7  8  9 10]
Berikut ini hasil dari penjumlahan matriks f dan g: 
[ 7  9 11 13 15]
Berikut ini hasil dari pengurangan matriks f dan g: 
[-5 -5 -5 -5 -5]
Berikut ini hasil dari perkalian matriks f dan g: 
[ 6 14 24 36 50]
Berikut ini hasil dari pembagian matriks f dan g: 
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Berikut ini hasil dari matriks g dipangkatkan f: 
[     6     49    512   6561 100000]


In [55]:
print('===Selamat datang di operasi skalar matriks===')
print('Ini adalah matriks yang akan dioperasikan :')
i_36 = np.array([1,1,2,3,5])      #menginisialisasi array i
print(i_36)
j_36 = np.array([8,13,21,34,55])     #menginisialisasi array j
print(j_36)

print('Berikut ini hasil dari penjumlahan matriks i dan j: ')
print(i_36+j_36)

print('Berikut ini hasil dari pengurangan matriks i dan j: ')
print(i_36-j_36)

print('Berikut ini hasil dari perkalian matriks i dan j: ')
print(i_36*j_36)

print('Berikut ini hasil dari pembagian matriks i dan j: ')
print(i_36/j_36)

print('Berikut ini hasil dari matriks i dipangkatkan j: ')
print(i_36**j_36)
print('===Terima kasih===')

===Selamat datang di operasi skalar matriks===
Ini adalah matriks yang akan dioperasikan :
[1 1 2 3 5]
[ 8 13 21 34 55]
Berikut ini hasil dari penjumlahan matriks i dan j: 
[ 9 14 23 37 60]
Berikut ini hasil dari pengurangan matriks i dan j: 
[ -7 -12 -19 -31 -50]
Berikut ini hasil dari perkalian matriks i dan j: 
[  8  13  42 102 275]
Berikut ini hasil dari pembagian matriks i dan j: 
[0.125      0.07692308 0.0952381  0.08823529 0.09090909]
Berikut ini hasil dari matriks i dipangkatkan j: 
[                1                 1           2097152 16677181699666569
 -3178808521666707]
===Terima kasih===


In [56]:
print('Ini adalah matriks yang akan dioperasikan :')
a_36 = np.array([6,7,8,9,10])       #menginisialisasi array a
print(a_36)


print('Berikut ini hasil dari penjumlahan matriks a ditambah 2: ')
print(a_36+2)

print('Berikut ini hasil dari pengurangan matriks a dikurang 2: ')
print(a_36-2)

print('Berikut ini hasil dari perkalian matriks a dikali 2: ')
print(a_36*2)

print('Berikut ini hasil dari pembagian matriks a dibagi 2: ')
print(a_36/2)

print('Berikut ini hasil dari matriks a dipangkatkan 2: ')
print(a_36**2)

Ini adalah matriks yang akan dioperasikan :
[ 6  7  8  9 10]
Berikut ini hasil dari penjumlahan matriks a ditambah 2: 
[ 8  9 10 11 12]
Berikut ini hasil dari pengurangan matriks a dikurang 2: 
[4 5 6 7 8]
Berikut ini hasil dari perkalian matriks a dikali 2: 
[12 14 16 18 20]
Berikut ini hasil dari pembagian matriks a dibagi 2: 
[3.  3.5 4.  4.5 5. ]
Berikut ini hasil dari matriks a dipangkatkan 2: 
[ 36  49  64  81 100]


In [57]:
print('Ini adalah matriks yang akan dioperasikan :')
d_36 = np.array([12,14,16,18,20,22,24,26,28])       #menginisialisasi array d
print(d_36)


print('Berikut ini hasil dari penjumlahan matriks d ditambah 2: ')
print(d_36+2)

print('Berikut ini hasil dari pengurangan matriks d dikurang 2: ')
print(d_36-2)

print('Berikut ini hasil dari perkalian matriks d dikali 2: ')
print(d_36*2)

print('Berikut ini hasil dari pembagian matriks d dibagi 2: ')
print(d_36/2)

print('Berikut ini hasil dari matriks d dipangkatkan 2: ')
print(d_36**2)

Ini adalah matriks yang akan dioperasikan :
[12 14 16 18 20 22 24 26 28]
Berikut ini hasil dari penjumlahan matriks d ditambah 2: 
[14 16 18 20 22 24 26 28 30]
Berikut ini hasil dari pengurangan matriks d dikurang 2: 
[10 12 14 16 18 20 22 24 26]
Berikut ini hasil dari perkalian matriks d dikali 2: 
[24 28 32 36 40 44 48 52 56]
Berikut ini hasil dari pembagian matriks d dibagi 2: 
[ 6.  7.  8.  9. 10. 11. 12. 13. 14.]
Berikut ini hasil dari matriks d dipangkatkan 2: 
[144 196 256 324 400 484 576 676 784]


In [58]:
# Fungsi Trigonometri pada Numpy
#Numpy menyediakan fungsi sin(), cos() dan tan() yang mengambil nilai dalam radian dan menghasilkan nilai sin, cos, dan tan yang seharusnya.

#a. np.cos(a)   => untuk mencari nilai cos masing-masing elemen pada a
#b. np.sin(a)   => untuk mencari nilai sin masing-masing elemen pada a
#c. np.tan(a)   => untuk mencari nilai tan masing-masing elemen pada a
#d. np.sinh(a)  => untuk mencari nilai invers/hiperbolik sin masing-masing elemen pada a
#e. np.cosh(a)  => untuk mencari nilai invers/hiperbolik cos masing-masing elemen pada a
#f. np.tanh(a)  => untuk mencari nilai invers/hiperbolik tan masing-masing elemen pada a
#g. np.sqrt(a)  => untuk mencari nilai akar kuadrat masing-masing elemen pada a

#Contoh 1 menemukan nilai sinus pi/2
o_36 = np.sin(np.pi/2)
print(o_36)
print('-----------------------------------------------------------')
#Contoh 2 menemukan nilai sinus untuk semua nilai di dataSudut
dataSudut_36 = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
p_36 = np.sin(dataSudut_36)
print(p_36)
print('-----------------------------------------------------------')
#Contoh 3 mengubah semua nilai dalam array berikut menjadi radian
sudutDerajat_36 = np.array([90, 180, 270, 360])
q_36 = np.deg2rad(sudutDerajat_36)
print(q_36)
print('-----------------------------------------------------------')
#Contoh 4 mengubah semua nilai dalam array berikut menjadi derajat
sudutRadian_36 = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
r_36 = np.rad2deg(sudutRadian_36)
print(r_36)

1.0
-----------------------------------------------------------
[1.         0.8660254  0.70710678 0.58778525]
-----------------------------------------------------------
[1.57079633 3.14159265 4.71238898 6.28318531]
-----------------------------------------------------------
[ 90. 180. 270. 360.]


## 2.20.6 Perkalian Matrik pada Numpy
Pada contoh sebelumnya, perkalian matriks dilakukan dengan mengoperasikan elemen yang baris dan kolomnya sama. Hal ini tentunya akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua matriks. Perkalian matrik pada Numpy dapat menggunakan perintah matmul. Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus sesuai dengan persyaratan. Misalnya matrik ukuran (1x2) dapat dikalikan dengan matrik ukuran (2x3)

In [59]:
print('Ini adalah matriks yang akan dioperasikan :')
print('b')
b_36 = np.array([[8,9,10,11],[12,13,14,15]])           #menginisialisasi array b => 2 x 4
print(b_36)
print('-------------------------------------------------')
print('c')
c_36 = np.array([[16,17,18,19],[20,21,22,23]])         #menginisialisasi array c => 2 x 4
print(c_36)
print('-------------------------------------------------')

#perkalian matriks b dan c tidak sesuai kaidah, karena memiliki ukuran yang tidak sesuai, output yang dihasilkan tentu tidak sesuai juga
print('Berikut ini hasil operasi perkalian matriks b dan c :')
d_36 = b_36*c_36
print(d_36)        #namun, output yang dihasilkan tidak sesuai dengan kaidah perkalian 2 matriks
#output yang dikasilkan seperti perkalian skalar karena kedua matriks memiliki ukuran yang sama

#kita coba gunakan matmul
# e_36 = np.matmul(b_36,c_36)
# print(t_36)

#outputnya yaitu
#  ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0,
  # with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

Ini adalah matriks yang akan dioperasikan :
b
[[ 8  9 10 11]
 [12 13 14 15]]
-------------------------------------------------
c
[[16 17 18 19]
 [20 21 22 23]]
-------------------------------------------------
Berikut ini hasil operasi perkalian matriks b dan c :
[[128 153 180 209]
 [240 273 308 345]]


In [60]:
#Contoh yang benar sesuai kaidah
print('Berikut adalah matriks yang akan dioperasikan :')
print('b')
b_36 = np.array([[8,9,10,11],[12,13,14,15]])          #menginisialisasi array b => 2 x 4
print(b_36)
print('-------------------------------------------------')
print('c')
e_36 = np.array([[16,17],[18,19],[20,21],[22,23]])    #menginisialisasi array e => 4 x 2
print(e_36)
print('-------------------------------------------------')
print('Berikut hasil operasi perkalian matriks b dan e :')
f_36 = np.matmul(b_36,e_36)
print(f_36)

# g_36 = a_36*e_36
# print(g_36)
#output error karena kedua matriks memiliki ukuran yang berbeda, sehingga perkalian skalar tidak terjadi

Berikut adalah matriks yang akan dioperasikan :
b
[[ 8  9 10 11]
 [12 13 14 15]]
-------------------------------------------------
c
[[16 17]
 [18 19]
 [20 21]
 [22 23]]
-------------------------------------------------
Berikut hasil operasi perkalian matriks b dan e :
[[ 732  770]
 [1036 1090]]


# 2.20.7 min,max dan sum pada Numpy

In [61]:
#menginisialisasi array
print('Berikut adalah matriks c :')
c_36 = np.array([[1,3,5,7],
            [9,11,13,15],
            [17,19,21,23]])
print (c_36)

print('Berikut adalah nilai minimum elemen pada matriks c :')
d_36 = np.min(c_36)
print(d_36)

print('Berikut adalah nilai minimum elemen baris pada masing-masing baris matriks c :')
e_36 = np.min(c_36, axis=1)
print(e_36)

print('Berikut adalah nilai minimum elemen kolom pada masing-masing baris matriks c :')
f_36 = np.min(c_36, axis=0)
print(f_36)

print('Berikut adalah nilai maksimum elemen pada matriks c :')
g_36 = np.max(c_36)
print(g_36)

print('Berikut adalah nilai maksimum elemen baris pada masing-masing baris matriks c :')
h_36 = np.max(c_36, axis=1)
print(h_36)

print('Berikut adalah nilai maksimum elemen kolom pada masing-masing baris matriks c :')
i_36 = np.max(c_36, axis=0)
print(i_36)

print('Berikut adalah jumlah nilai semua elemen pada matriks c :')
j_36 = np.sum(c_36)
print(j_36)

print('Berikut adalah jumlah nilai elemen pada masing-masing kolom matriks c :')
j_36=np.sum(c_36,axis=0)
print(j_36)

print('Berikut adalah jumlah nilai elemen pada masing-masing baris matriks c :')
k_36 = np.sum(c_36,axis=1)
print(k_36)

Berikut adalah matriks c :
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
Berikut adalah nilai minimum elemen pada matriks c :
1
Berikut adalah nilai minimum elemen baris pada masing-masing baris matriks c :
[ 1  9 17]
Berikut adalah nilai minimum elemen kolom pada masing-masing baris matriks c :
[1 3 5 7]
Berikut adalah nilai maksimum elemen pada matriks c :
23
Berikut adalah nilai maksimum elemen baris pada masing-masing baris matriks c :
[ 7 15 23]
Berikut adalah nilai maksimum elemen kolom pada masing-masing baris matriks c :
[17 19 21 23]
Berikut adalah jumlah nilai semua elemen pada matriks c :
144
Berikut adalah jumlah nilai elemen pada masing-masing kolom matriks c :
[27 33 39 45]
Berikut adalah jumlah nilai elemen pada masing-masing baris matriks c :
[16 48 80]


In [62]:
print('Berikut adalah matriks m :')
m_36 = np.array([[12,14,16,18],
            [20,22,24,26],
            [28,30,32,34]])
print (m_36)

print('Berikut adalah nilai minimum elemen pada matriks m :')
n_36 = np.min(m_36)
print(n_36)

print('Berikut adalah nilai minimum elemen baris pada masing-masing baris matriks m :')
o_36 = np.min(m_36, axis=1)
print(o_36)

print('Berikut adalah nilai minimum elemen kolom pada masing-masing baris matriks m :')
p_36 = np.min(m_36, axis=0)
print(p_36)

print('Berikut adalah nilai maksimum elemen pada matriks m :')
q_36 = np.max(m_36)
print(q_36)

print('Berikut adalah nilai maksimum elemen baris pada masing-masing baris matriks m :')
r_36 = np.max(m_36, axis=1)
print(r_36)

print('Berikut adalah nilai maksimum elemen kolom pada masing-masing baris matriks m :')
s_36 = np.max(m_36, axis=0)
print(s_36)

print('Berikut adalah jumlah nilai semua elemen pada matriks m :')
t_36 = np.sum(m_36)
print(t_36)

print('Berikut adalah jumlah nilai elemen pada masing-masing kolom matriks m :')
t_36=np.sum(m_36,axis=0)
print(t_36)

print('Berikut adalah jumlah nilai elemen pada masing-masing baris matriks m :')
u_36 = np.sum(m_36,axis=1)
print(u_36)

Berikut adalah matriks m :
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Berikut adalah nilai minimum elemen pada matriks m :
12
Berikut adalah nilai minimum elemen baris pada masing-masing baris matriks m :
[12 20 28]
Berikut adalah nilai minimum elemen kolom pada masing-masing baris matriks m :
[12 14 16 18]
Berikut adalah nilai maksimum elemen pada matriks m :
34
Berikut adalah nilai maksimum elemen baris pada masing-masing baris matriks m :
[18 26 34]
Berikut adalah nilai maksimum elemen kolom pada masing-masing baris matriks m :
[28 30 32 34]
Berikut adalah jumlah nilai semua elemen pada matriks m :
276
Berikut adalah jumlah nilai elemen pada masing-masing kolom matriks m :
[60 66 72 78]
Berikut adalah jumlah nilai elemen pada masing-masing baris matriks m :
[ 60  92 124]
